### ISSUE TITLE
'unexpressed' now superfluous?

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#587] opened 2021-02-19 17:13 UTC
The type 'unexpressed' is still used in several places in the grammar, but I think its only function was to provide specific NON-LOCAL values so as to not break the appends in the lexical threading analysis of LDDs. If this is correct, this type can be removed, and probably should be, as such relics are just confusing.

**Comment by olzama** [comment] 2021-06-10 20:39
Duplicate of #594 (which is later but has more information in it).

**Closed as completed by olzama** 2021-06-10 20:39 UTC
Labels: duplicate
